name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  NXF_SYNTAX_PARSER: "v2"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: nf-core/setup-nextflow@v2
      - uses: pre-commit/action@v3.0.1
