name: Run plugin tests
on:
  push:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

permissions:
  contents: read

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  NXF_SYNTAX_PARSER: "v2"
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["17", "21"]
        nextflow-version:
          - "26.01.1-edge"
          - "latest-everything"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: ${{ matrix.nextflow-version }}

      - name: Check tools
        shell: bash -el {0}
        run: |
          java --version
          mvn --version
          nextflow -version
          nf-test version
          nf-core --version

      - name: Build plugin
        shell: bash -el {0}
        run: ./build.sh

      - name: Test plugin
        shell: bash -el {0}
        run: ./test.sh
