name: Run plugin tests
on:
  push:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]

permissions:
  contents: read

env:
  NFT_WORKDIR: "~"
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  NXF_SYNTAX_PARSER: "v2"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        JAVA_VERSION: ["17", "21"]
        NXF_VER:
          - "26.01.1-edge"
          - "latest-everything"

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}
          cache: maven

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Setup Nextflow ${{ matrix.NXF_VER }}
        uses: nf-core/setup-nextflow@893c28b667aedeba26e37f296d260ccc5bc4d914 # v3
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Build plugin
        shell: bash -el {0}
        run: ./build.sh

      - name: Test plugin
        shell: bash -el {0}
        run: ./test.sh
